### ISSUE TITLE
Create one-page summary of proposal

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/iuse2014#10]
Please add a one-page summary of the proposal to the front of `proposal.tex`.

**Comment by labarba** [comment]
Please note, from NSF GPG that FastLane will give you:
... three separate text boxes in which proposers must provide an Overview and address the “Intellectual Merit’ and “Broader Impacts” of the proposed activity.
You might as well separate these out on the document, as you'll have to enter them separately in FastLane and they still need to be within the one page.

**Comment by labarba** [comment]
The summary page currently in the proposal needs some work—the text already there should be summarized to become the "Overview" paragraph, and the new paragraphs for "Intellectual Merit" and "Broader Impacts" should be written.

IM and BI should be addressed both in the main proposal text and the summary.
