### ISSUE TITLE
Be explicit about conferences/journals where results can be published

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/iuse2014#15]
- SIGCSE (for the computing side)
- ICPE (for the science side)
- [ABLE](http://www.ableweb.org/): can we persuade them that computing counts as lab?

**Comment by rachelslaybaugh** [comment]
I'm not sure what ICPE is. International Conference on Performance Engineering?

Useful resource: http://www.sigcse.org/resources/publish

Other places I've thought of: 
- Society for Industrial and Applied Mathematics (SIAM; their education committee gets a conference talk slot)
- American Nuclear Society (ANS; there are education tracks at their national meetings and I go to these anyway)
