### ISSUE TITLE
Include discussion of research computing consortium.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/iuse2014#18]
If possible, add discussion of interactions with research computing consortium.

**Comment by gonuke** [comment]
Should I introduce this as:
1. a place in which we intend to offer workshops in years 2-5 as part of the project, OR
2. a mechanism to disseminate the curriculum outside of the project?

Thoughts?

**Comment by gonuke** [comment]
Not sure who is following these issues. The creator should be automatic, but I'm pinging @rachelslaybaugh as well.

**Comment by gvwilson** [comment]
Please do both:
1. These are venues we are likely to grow into during years 2-5.  (You're right, we won't be there in year 1 because we're only budgeted for 2 out-of-core workshops that year, and they're for women and underrepresented students respectively.)
2. They are likely targets for dissemination of curriculum (although we have no way to make promises).
3. They're venues for us to see whether THW-style groups can be launched _without_ our explicit support (i.e., without us paying for a grad student assistant).

Thanks.
