### ISSUE TITLE
Write career management plan for part-time grad students.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/iuse2014#20]
And possibly for the assessor and instructional designer? (Hard to know whether to do that if they're going to be professionals rather than grad students?)  There's a fixme in proposal.tex.

**Comment by ethanwhite** [comment]
I just put in a PR addressing the grad students. The person mentoring the assessor and instructional designer should write the section related to them. If they are postdocs that will need to be in a formal (separate) Postdoc Mentoring Plan.
