### ISSUE TITLE
Need current and pending support for @gonuke

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/iuse2014#51]

**Comment by gonuke** [comment]
This was sent to @rachelslaybaugh on 1/26/14

**Comment by gvwilson** [comment]
Thanks - @rachelslaybaugh, can you please commit to the repo when you 
get a sec?

**Comment by gonuke** [comment]
Reopening to reformat to LaTeX

**Comment by gonuke** [comment]
Addressed in #52, but awaiting a final number I realized I was missing...
