### ISSUE TITLE
Results of past NSF support for @ctb

### ISSUE THREAD

**Issue by ctb** [swcarpentry/iuse2014#54]
Not sure where to put this, but here's the text --

Brown - Project Proposal Title: Symbiont Separation and Investigation of the Novel Heterotrophic Osedax Symbiosis using Comparative Genomics; NSF 09-23812 (PI Brown); Project Location: Michigan State University; Total Award Amount: $50k; Starting Date: 01/01/10; Ending Date: 12/31/13. This project was a collaborative project with Dr. Shana Goffredi at Occidental College, where we analyzed sequence from MDA-amplified metagenomic samples taken from an Osedax bone eating worm. We produced the first high-quality assemblies of two symbiont genomes, giving us a whole-genome perspective on symbiont metabolism. This work was published in ISME J in November 2013 (PubMed ID 24225886).

**Comment by rachelslaybaugh** [comment]
added to the proposal!
