### ISSUE TITLE
Scope of work for MSU

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/iuse2014#59]
Need scope of work for @ctb and @tracykteal

**Comment by ctb** [comment]
@tracykteal if you write something I can review & edit it... what an offer, eh?

**Comment by tracykteal** [comment]
Ethan already wrote something that I modified.  Attached.

**Comment by gvwilson** [comment]
Perfectly OK to change names in the following and send it back:

Dr. Ethan White and a graduate student RA will organize and teach one
2-3 day Software Carpentry workshop targeted for students in the
National Science Foundation's Research Experience for Undergraduate
program at the beginning of each summer of the project (2015-2019).
This workshop will teach fundamental scientific computing skills to
these students.  Following the workshop the graduate student will meet
regularly with the undergraduates to provide further training,
technical support, and mentoring with respect to computational methods
and approaches to science.

**Comment by ctb** [comment]
"attached"?
